### ISSUE TITLE
Is it possible to get a model artifact? 

### ISSUE THREAD

**Issue by gear** [miargentieri/proteomic-age-ukb#1]
Hi, thank you for sharing the code for your paper! 

I'm a researcher working on healthy ageing, I wonder is it possible for you to send me your trained model (as a pickle file for example) for evaluation?

**Comment by miargentieri** [comment]
Unfortunately our university will not currently allow us to share the actual trained model file. However, we are preparing to release software in the near future that will allow users to calculate the proteomic age clock in their own samples using our pre-trained model. We will update this repository as that develops. A near term alternative is that if you are able to share you data with us, we can calculate the proteomic age clock for you (this will also require some specific renormalization for the model to work correctly). If this is of interest, please get in touch via email!
